sudo:required

services:
  - docker

before_install:
  - docker build -t muhammadhaziq/react-app:latest -f Dockerfile.dev .

script:
  - docker run -e CI=true muhammadhaziq/react-app:latest npm run test