name: Deploy Frontend
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #https://github.com/marketplace/actions/checkout
      #if u want to install latest node version u can check above doc and search node js in it
      - uses: actions/checkout@v4
      - run: echo "Login to Docker Hub"
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: echo "Build and push Docker image"
      - run: docker build -t muhammadhaziq/react-test -f Dockerfile.dev .
      - run: echo "Run tests"
      - run: docker run -e CI=true muhammadhaziq/react-test npm test
