name: Stage
on:
  push:
    branches:
      - develop
    paths-ignore:
      - ".github/workflows/*"
      - "README.md"
  pull_request:
    branches:
      - develop
jobs:
  run-test-cases:
    runs-on: ubuntu-latest
    steps:
      #https://github.com/marketplace/actions/checkout
      #if u want to install latest node version u can check above doc and search node js in it
      - uses: actions/checkout@v4
      - run: echo "Login to Docker Hub"
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: echo "Build Docker image"
      - run: docker build -t muhammadhaziq/react-test -f Dockerfile.dev .
      - run: echo "Run tests"
      - run: docker run -e CI=true muhammadhaziq/react-test npm test

  build-and-deploy:
    needs: run-test-cases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Login to Docker Hub"
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: echo "Build Docker Image"
      - run: docker build -t muhammadhaziq/react-test .
      - run: echo "Run Docker Image"
      - run: docker run -d -p 8080:80 muhammadhaziq/react-test
      - run: echo "Deploying Docker Image"
